CC=cc

.PHONY: all insertion merge

all: insertion merge

insertion:
	$(CC) -g -ansi -std=gnu99 -Wall insertion.c -o insertion

merge:
	$(CC) -g -ansi -std=gnu99 -Wall merge.c -o merge

clean:
	rm -rf insertion merge
